/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Laporan;

import Class.Fungsi;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;

/**
 *
 * @author Hanii
 */
public class dialogCetak extends javax.swing.JDialog {

    /**
     * Creates new form dialogCetak
     */
    String kondisi = "";
    private String tampilan = "yyyy-MM-dd";
    SimpleDateFormat format = new SimpleDateFormat(tampilan);
    Fungsi fungsi = new Fungsi();
    public dialogCetak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent we) {
        if(CBPilih.getSelectedItem().equals("SESUAIKAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(true);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("HARIAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(true);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("BULANAN")){
            pBulanan.setVisible(true);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
            if(cekTahun.isSelected()){
                getTahunBulan.setVisible(true);
            }else{
                getTahunBulan.setVisible(false);
            }
        }else if(CBPilih.getSelectedItem().equals("TAHUNAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(true);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("SEMUA")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }
                super.windowActivated(we); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowClosed(WindowEvent we) {
                dispose();
                super.windowClosed(we); //To change body of generated methods, choose Tools | Templates.
            }
            });
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBPilih = new javax.swing.JComboBox<>();
        pSesuaikan = new javax.swing.JPanel();
        fromDate = new com.toedter.calendar.JDateChooser();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        pHarian = new javax.swing.JPanel();
        getHari = new com.toedter.calendar.JCalendar();
        pBulanan = new javax.swing.JPanel();
        getbulan = new com.toedter.calendar.JMonthChooser();
        cekTahun = new javax.swing.JCheckBox();
        getTahunBulan = new com.toedter.calendar.JYearChooser();
        pTahunan = new javax.swing.JPanel();
        getTahun = new com.toedter.calendar.JYearChooser();
        pButton = new javax.swing.JPanel();
        bCetak = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setText("FILTER DATA");

        CBPilih.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        CBPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "SESUAIKAN", "HARIAN", "BULANAN", "TAHUNAN" }));
        CBPilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBPilihItemStateChanged(evt);
            }
        });
        CBPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBPilihMouseClicked(evt);
            }
        });

        pSesuaikan.setBackground(new java.awt.Color(0, 204, 204));
        pSesuaikan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Tanggal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 0, 11))); // NOI18N

        fromDate.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N

        toDate.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel2.setText("sampai dengan");

        javax.swing.GroupLayout pSesuaikanLayout = new javax.swing.GroupLayout(pSesuaikan);
        pSesuaikan.setLayout(pSesuaikanLayout);
        pSesuaikanLayout.setHorizontalGroup(
            pSesuaikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSesuaikanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSesuaikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pSesuaikanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pSesuaikanLayout.setVerticalGroup(
            pSesuaikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSesuaikanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pHarian.setBackground(new java.awt.Color(0, 204, 204));
        pHarian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Tanggal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 0, 11))); // NOI18N

        javax.swing.GroupLayout pHarianLayout = new javax.swing.GroupLayout(pHarian);
        pHarian.setLayout(pHarianLayout);
        pHarianLayout.setHorizontalGroup(
            pHarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHarianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pHarianLayout.setVerticalGroup(
            pHarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHarianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pBulanan.setBackground(new java.awt.Color(0, 204, 204));
        pBulanan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Bulan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 0, 11))); // NOI18N

        getbulan.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        getbulan.setMonth(0);
        getbulan.setOpaque(false);
        getbulan.setYearChooser(null);

        cekTahun.setBackground(new java.awt.Color(0, 204, 204));
        cekTahun.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        cekTahun.setSelected(true);
        cekTahun.setText("TAHUN");
        cekTahun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cekTahunItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pBulananLayout = new javax.swing.GroupLayout(pBulanan);
        pBulanan.setLayout(pBulananLayout);
        pBulananLayout.setHorizontalGroup(
            pBulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBulananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getTahunBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cekTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        pBulananLayout.setVerticalGroup(
            pBulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBulananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getTahunBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pTahunan.setBackground(new java.awt.Color(0, 204, 204));
        pTahunan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Tahun", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 0, 11))); // NOI18N

        javax.swing.GroupLayout pTahunanLayout = new javax.swing.GroupLayout(pTahunan);
        pTahunan.setLayout(pTahunanLayout);
        pTahunanLayout.setHorizontalGroup(
            pTahunanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTahunanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTahunanLayout.setVerticalGroup(
            pTahunanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTahunanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pButton.setBackground(new java.awt.Color(0, 204, 204));

        bCetak.setBackground(new java.awt.Color(153, 255, 153));
        bCetak.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        bCetak.setText("CETAK DATA");
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        bSimpan.setBackground(new java.awt.Color(153, 255, 153));
        bSimpan.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        bSimpan.setText("SAVE AS PDF");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButtonLayout = new javax.swing.GroupLayout(pButton);
        pButton.setLayout(pButtonLayout);
        pButtonLayout.setHorizontalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pButtonLayout.setVerticalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSimpan)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CBPilih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSesuaikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pHarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBulanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTahunan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSesuaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTahunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        // TODO add your handling code here:
        
        if(CBPilih.getSelectedItem().equals("SESUAIKAN")){
            String form = String.valueOf(format.format(fromDate.getDate()));
            String to = String.valueOf(format.format(toDate.getDate()));
            System.out.println(form+"   "+to);
            kondisi = "WHERE `Tanggal_Beli` BETWEEN '"+form+"' AND '"+to+"'";
        }else if(CBPilih.getSelectedItem().equals("HARIAN")){
            String hari = String.valueOf(format.format(getHari.getDate()));
            kondisi = "WHERE `Tanggal_Beli` = '"+hari+"'";
        }else if(CBPilih.getSelectedItem().equals("BULANAN")){
            int bulan = getbulan.getMonth()+1;
            if(cekTahun.isSelected()){
                kondisi = "WHERE MONTH(tanggal_beli)="+bulan+" AND YEAR(tanggal_beli)="+getTahunBulan.getYear()+"";
            }else{
                kondisi = "WHERE MONTH(tanggal_beli)="+bulan+"";
            }
        }else if(CBPilih.getSelectedItem().equals("TAHUNAN")){
            kondisi = "WHERE YEAR(tanggal_beli)="+getTahunBulan.getYear()+"";
        }else if(CBPilih.getSelectedItem().equals("SEMUA")){
            kondisi="";
        }
        String SQL = "SELECT\n" +
"\n" +
"     strukpembayaran.`ID_Struk` AS ID_Struk,\n" +
"     strukpembayaran.`Tanggal_Beli` AS Tanggal_Beli,\n" +
"     strukpembayaran.`Jam_Beli` AS Jam_Beli,\n" +
"     relasi_pesantiket.`Judul_Film` AS Judul_Film,\n" +
"     strukpembayaran.`Jumlah_Item` AS Jumlah_Item,\n" +
"     strukpembayaran.`Total` AS Total,\n" +
"     (Diskon*Total)*0.1 AS Diskon,\n" +
"     strukpembayaran.`Total_Bayar` AS Total_Bayar,\n" +
"     strukpembayaran.`Nama_Kasir` AS Nama_Kasir\n" +
"FROM\n" +
"     `strukpembayaran` strukpembayaran INNER JOIN `relasi_pesantiket` relasi_pesantiket ON strukpembayaran.`ID_Struk` = relasi_pesantiket.`ID_Struk` "+kondisi;
        
        
        fungsi.Cetak(SQL, "LaporanTransaksi",1);
    }//GEN-LAST:event_bCetakActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if(CBPilih.getSelectedItem().equals("SESUAIKAN")){
            String form = String.valueOf(format.format(fromDate.getDate()));
            String to = String.valueOf(format.format(toDate.getDate()));
            System.out.println(form+"   "+to);
            kondisi = "WHERE `Tanggal_Beli` BETWEEN '"+form+"' AND '"+to+"'";
        }else if(CBPilih.getSelectedItem().equals("HARIAN")){
            String hari = String.valueOf(format.format(getHari.getDate()));
            kondisi = "WHERE `Tanggal_Beli` = '"+hari+"'";
        }else if(CBPilih.getSelectedItem().equals("BULANAN")){
            int bulan = getbulan.getMonth()+1;
            if(cekTahun.isSelected()){
                kondisi = "WHERE MONTH(tanggal_beli)="+bulan+" AND YEAR(tanggal_beli)="+getTahunBulan.getYear()+"";
            }else{
                kondisi = "WHERE MONTH(tanggal_beli)="+bulan+"";
            }
        }else if(CBPilih.getSelectedItem().equals("TAHUNAN")){
            kondisi = "WHERE YEAR(tanggal_beli)="+getTahunBulan.getYear()+"";
        }else if(CBPilih.getSelectedItem().equals("SEMUA")){
            kondisi="";
        }
        String SQL = "SELECT\n" +
"\n" +
"     strukpembayaran.`ID_Struk` AS ID_Struk,\n" +
"     strukpembayaran.`Tanggal_Beli` AS Tanggal_Beli,\n" +
"     strukpembayaran.`Jam_Beli` AS Jam_Beli,\n" +
"     relasi_pesantiket.`Judul_Film` AS Judul_Film,\n" +
"     strukpembayaran.`Jumlah_Item` AS Jumlah_Item,\n" +
"     strukpembayaran.`Total` AS Total,\n" +
"     (Diskon*Total)*0.1 AS Diskon,\n" +
"     strukpembayaran.`Total_Bayar` AS Total_Bayar,\n" +
"     strukpembayaran.`Nama_Kasir` AS Nama_Kasir\n" +
"FROM\n" +
"     `strukpembayaran` strukpembayaran INNER JOIN `relasi_pesantiket` relasi_pesantiket ON strukpembayaran.`ID_Struk` = relasi_pesantiket.`ID_Struk` "+kondisi;
        
       fungsi.savePDF("LaporanTransaksi", SQL);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void CBPilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBPilihMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CBPilihMouseClicked

    private void CBPilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBPilihItemStateChanged
        // TODO add your handling code here:
        if(CBPilih.getSelectedItem().equals("SESUAIKAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(true);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("HARIAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(true);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("BULANAN")){
            pBulanan.setVisible(true);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("TAHUNAN")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(true);
            pButton.setVisible(true);
        }else if(CBPilih.getSelectedItem().equals("SEMUA")){
            pBulanan.setVisible(false);
            pHarian.setVisible(false);
            pSesuaikan.setVisible(false);
            pTahunan.setVisible(false);
            pButton.setVisible(true);
        }
    }//GEN-LAST:event_CBPilihItemStateChanged

    private void cekTahunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cekTahunItemStateChanged
        // TODO add your handling code here:
        if(cekTahun.isSelected()){
                getTahunBulan.setVisible(true);
            }else{
                getTahunBulan.setVisible(false);
            }
    }//GEN-LAST:event_cekTahunItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogCetak dialog = new dialogCetak(new javax.swing.JFrame(), true);
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPilih;
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bSimpan;
    private javax.swing.JCheckBox cekTahun;
    private com.toedter.calendar.JDateChooser fromDate;
    private com.toedter.calendar.JCalendar getHari;
    private com.toedter.calendar.JYearChooser getTahun;
    private com.toedter.calendar.JYearChooser getTahunBulan;
    private com.toedter.calendar.JMonthChooser getbulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBulanan;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pHarian;
    private javax.swing.JPanel pSesuaikan;
    private javax.swing.JPanel pTahunan;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
