/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.DataFilm;


import Class.Fungsi;
import static Main.panelIdentitas.panelidentitas;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JList;

/**
 *
 * @author dadan
 */
public class panelDeskripsiFilm extends javax.swing.JPanel {

    /**
     * Creates new form panelDeskripsiFilm
     */
    JList list = new JList();
    String data[] = new String[0];
        String SQL, idFilmD, deskripsiFilmD, listAktorD = null;
        Vector listTampilAktor;
        int row = 0,gnt = 0;
    ResultSet res = null;
    Fungsi fungsi = new Fungsi();
    public panelDeskripsiFilm() throws SQLException {
        initComponents();
        tampilFilm();tampilAktor();
        
    }
    
    public void tampilFilm() throws SQLException{
        setAkses();
        data = new String[7];
        SQL = "SELECT ID_Film, Judul_Film, Tahun_Film, Nama_Genre, DurasiFilm, Sutradara, Deskripsi  FROM `film`, `film.genre` "
            + "WHERE ID_Film = '"+idFilmD+"' AND `film`.`ID_Genre`=`film.genre`.`ID_Genre` ORDER BY ID_Film";
        data = koneksi.ambilData(7, SQL);
        LIDFilmD.setText(data[0]);
        LJudulFilm.setText(data[1]);
        LTahun.setText(data[2].substring(0, 4));
        LGenre.setText(data[3]);
        LMenit.setText(data[4]);
        LSutradara.setText(data[5]);
        LDeskripsi.setText(data[6]);
        jLabelGambar.setIcon(fungsi.gtGambar("Poster", "SELECT Poster FROM film WHERE ID_Film = '"+idFilmD+"'",151,177));
        this.idFilmD = data[0];
        this.deskripsiFilmD =data[6];
    }
    public void tampilAktor() throws SQLException{
            listAktorD = new String();
            listAktorD = null;
            SQL = "SELECT Aktor FROM `film.aktor` WHERE ID_Film = '"+idFilmD+"'";
            res = koneksi.lihatData(SQL);
            if(res.last()){
                this.row = res.getRow();
                res.beforeFirst();
            }            
            while(res.next()){
                for (int i = 0; i < this.row; i++) {
                    if(this.listAktorD == null){
                        this.listAktorD = res.getString(i+1);
                    }else if(listAktorD!=null){
                        this.listAktorD = this.listAktorD+", "+res.getString(i+1);
                    }         
                    break;
                }
                LAktor.setText(this.listAktorD);
            }
    }
    public void setAkses() throws SQLException{
        data = new String[1];
        data = koneksi.ambilData(1, "SELECT * FROM dummyHelp");
        this.idFilmD = data[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PDeskripsiFilm = new javax.swing.JPanel();
        LJudulFilm = new javax.swing.JLabel();
        LGenre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LMenit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LSutradara = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LAktor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LTahun = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LDeskripsi = new javax.swing.JTextArea();
        LIDFilmD = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        PDeskripsiFilm.setBackground(new java.awt.Color(204, 255, 255));

        LJudulFilm.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        LJudulFilm.setText("JUDUL FILM");

        LGenre.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LGenre.setText("Genre");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("•");

        LMenit.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        LMenit.setText("00");

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel6.setText("minutes");

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel7.setText("Sutradara");

        LSutradara.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LSutradara.setText("Nama Sutradara");

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel9.setText("Aktor");

        LAktor.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LAktor.setText("Nama-Nama Aktor");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("•");

        LTahun.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LTahun.setText("Tahun");

        jPanel13.setBackground(new java.awt.Color(153, 255, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESKRIPSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        LDeskripsi.setEditable(false);
        LDeskripsi.setBackground(new java.awt.Color(153, 255, 153));
        LDeskripsi.setColumns(20);
        LDeskripsi.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LDeskripsi.setLineWrap(true);
        LDeskripsi.setRows(5);
        LDeskripsi.setText("Isi Deskripsi");
        LDeskripsi.setBorder(null);
        jScrollPane2.setViewportView(LDeskripsi);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        LIDFilmD.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        LIDFilmD.setForeground(new java.awt.Color(255, 51, 51));
        LIDFilmD.setText("LIDFILM");

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGambarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PDeskripsiFilmLayout = new javax.swing.GroupLayout(PDeskripsiFilm);
        PDeskripsiFilm.setLayout(PDeskripsiFilmLayout);
        PDeskripsiFilmLayout.setHorizontalGroup(
            PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PDeskripsiFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                        .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                                .addComponent(LJudulFilm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LIDFilmD))
                            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                                .addComponent(LGenre)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(LMenit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(LTahun))
                            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                                .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(LSutradara)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LAktor))))
                        .addGap(0, 290, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PDeskripsiFilmLayout.setVerticalGroup(
            PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJudulFilm)
                    .addComponent(LIDFilmD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LGenre)
                    .addComponent(jLabel4)
                    .addComponent(LMenit)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(LTahun))
                .addGap(18, 18, 18)
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LSutradara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LAktor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(PDeskripsiFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(PDeskripsiFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGambarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelGambarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelidentitas.JS.setViewportView(new panelFilm());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAktor;
    private javax.swing.JTextArea LDeskripsi;
    private javax.swing.JLabel LGenre;
    private javax.swing.JLabel LIDFilmD;
    private javax.swing.JLabel LJudulFilm;
    private javax.swing.JLabel LMenit;
    private javax.swing.JLabel LSutradara;
    private javax.swing.JLabel LTahun;
    private javax.swing.JPanel PDeskripsiFilm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
