/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Tiket.PilihTiket;

import Class.Fungsi;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dadan
 */
public class panelDeskripsiPilihFilm extends javax.swing.JPanel {

    /**
     * Creates new form panelDeskripsiPilihFilm
     */
    Fungsi fungsi = new Fungsi();
    String studio,idFilmD,SQL,listAktorD = null;
    ResultSet res;
    int row = 0;
    
    
    public panelDeskripsiPilihFilm() throws SQLException {
        initComponents();
        panelDeskripsi.setVisible(false);
        LTutup.setVisible(false);
        tampilFilm();
    }
    public void tampilFilm() throws SQLException{
        setAkses();
        String data[] = new String[7];
        SQL = "SELECT ID_Film, Judul_Film, Tahun_Film, Nama_Genre, DurasiFilm, Sutradara, Deskripsi  FROM `film`, `film.genre` "
            + "WHERE ID_Film = '"+idFilmD+"' AND `film`.`ID_Genre`=`film.genre`.`ID_Genre` ORDER BY ID_Film";
        data =  koneksi.ambilData(7, SQL);
        LJudulFilm.setText(data[1]);
        LTahun.setText(data[2].substring(0, 4));
        LGenre.setText(data[3]);
        LMenit.setText(data[4]);
        LSutradara.setText(data[5]);
        LDeskripsi.setText(data[6]);
        LStudio.setText(studio);
        jLabelGambar.setIcon( fungsi.gtGambar("Poster", "SELECT Poster FROM film WHERE ID_Film = '"+idFilmD+"'",163,195));
        tampilAktor();
    }
    public void tampilAktor() throws SQLException{
        
            listAktorD = new String();
            listAktorD = null;
            SQL = "SELECT Aktor FROM `film.aktor` WHERE ID_Film = '"+this.idFilmD+"'";
            res =  koneksi.lihatData(SQL);
            if(res.last()){
                this.row = res.getRow();
                res.beforeFirst();
            }            
            while(res.next()){
                for (int i = 0; i < this.row; i++) {
                    if(this.listAktorD == null){
                        this.listAktorD = res.getString(i+1);
                    }else if(listAktorD!=null){
                        this.listAktorD = this.listAktorD+", "+res.getString(i+1);
                    }         
                    break;
                }
                LAktor.setText(this.listAktorD);
            }
    }
    public void setAkses() throws SQLException{
        String data[] = new String[1];
        data =  koneksi.ambilData(1, "SELECT * FROM dummyHelp");
        this.studio = data[0];
        
        data =  koneksi.ambilData(1, "SELECT ID_Film FROM jadwal where Studio='"+this.studio+"'");
        this.idFilmD = data[0];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PDeskripsiFilm = new javax.swing.JPanel();
        LJudulFilm = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        LGenre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LMenit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LSutradara = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelDeskripsi = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LDeskripsi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        LBaca = new javax.swing.JLabel();
        LTutup = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LTahun = new javax.swing.JLabel();
        LStudio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LAktor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        PDeskripsiFilm.setBackground(new java.awt.Color(204, 255, 255));

        LJudulFilm.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        LJudulFilm.setText("JUDUL FILM");

        LGenre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LGenre.setText("Genre");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("•");

        LMenit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LMenit.setText("00");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("minutes");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel7.setText("Sutradara");

        LSutradara.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LSutradara.setText("Nama Sutradara");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel9.setText("Aktor");

        panelDeskripsi.setBackground(new java.awt.Color(153, 255, 153));
        panelDeskripsi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESKRIPSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jScrollPane2.setBorder(null);

        LDeskripsi.setBackground(new java.awt.Color(153, 255, 153));
        LDeskripsi.setColumns(20);
        LDeskripsi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LDeskripsi.setLineWrap(true);
        LDeskripsi.setRows(5);
        LDeskripsi.setText("Isi Deskripsi");
        LDeskripsi.setBorder(null);
        jScrollPane2.setViewportView(LDeskripsi);

        javax.swing.GroupLayout panelDeskripsiLayout = new javax.swing.GroupLayout(panelDeskripsi);
        panelDeskripsi.setLayout(panelDeskripsiLayout);
        panelDeskripsiLayout.setHorizontalGroup(
            panelDeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelDeskripsiLayout.setVerticalGroup(
            panelDeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("•");

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGambarMouseClicked(evt);
            }
        });

        LBaca.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        LBaca.setForeground(new java.awt.Color(255, 51, 51));
        LBaca.setText("BACA RINGKASAN");
        LBaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBacaMouseClicked(evt);
            }
        });

        LTutup.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        LTutup.setForeground(new java.awt.Color(255, 51, 51));
        LTutup.setText("KEMBALI");
        LTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LTutupMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setText("PILIH JADWAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LTahun.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTahun.setText("Tahun");

        LStudio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LStudio.setText("Studio");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("•");

        jScrollPane3.setBorder(null);

        LAktor.setBackground(new java.awt.Color(204, 255, 255));
        LAktor.setColumns(20);
        LAktor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LAktor.setLineWrap(true);
        LAktor.setRows(1);
        LAktor.setTabSize(1);
        LAktor.setText("Nama-Nama Aktor");
        LAktor.setBorder(null);
        jScrollPane3.setViewportView(LAktor);

        javax.swing.GroupLayout PDeskripsiFilmLayout = new javax.swing.GroupLayout(PDeskripsiFilm);
        PDeskripsiFilm.setLayout(PDeskripsiFilmLayout);
        PDeskripsiFilmLayout.setHorizontalGroup(
            PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LJudulFilm)
                        .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                            .addComponent(LGenre)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(LMenit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(LTahun)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(LStudio))
                        .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                            .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                                    .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LSutradara)
                                        .addComponent(jLabel9)
                                        .addComponent(LBaca))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LTutup)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))))
                    .addComponent(panelDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PDeskripsiFilmLayout.setVerticalGroup(
            PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudulFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LGenre)
                    .addComponent(jLabel4)
                    .addComponent(LMenit)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(LTahun)
                    .addComponent(LStudio)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PDeskripsiFilmLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LSutradara)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PDeskripsiFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBaca)
                            .addComponent(LTutup)))
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 246;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 2, 10);
        jPanel3.add(PDeskripsiFilm, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu.Tiket.panelTiketUtama.formpilihtiket.jPanel2.setVisible(true);
        Menu.Tiket.panelTiketUtama.formpilihtiket.JS.setViewportView(new panelPilihFilm());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGambarMouseClicked
       
    }//GEN-LAST:event_jLabelGambarMouseClicked

    private void LBacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBacaMouseClicked
        // TODO add your handling code here:
        LBaca.setVisible(false);
        panelDeskripsi.setVisible(true);
        LTutup.setVisible(true);
        jButton2.setVisible(false);
    }//GEN-LAST:event_LBacaMouseClicked

    private void LTutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LTutupMouseClicked
        // TODO add your handling code here:
        LBaca.setVisible(true);
        panelDeskripsi.setVisible(false);
        LTutup.setVisible(false);
        jButton2.setVisible(true);
    }//GEN-LAST:event_LTutupMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
        Menu.Tiket.panelTiketUtama.formpilihtiket.JS.setViewportView(new panelPilihJadwal());
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LAktor;
    private javax.swing.JLabel LBaca;
    private javax.swing.JTextArea LDeskripsi;
    private javax.swing.JLabel LGenre;
    private javax.swing.JLabel LJudulFilm;
    private javax.swing.JLabel LMenit;
    public javax.swing.JLabel LStudio;
    private javax.swing.JLabel LSutradara;
    private javax.swing.JLabel LTahun;
    private javax.swing.JLabel LTutup;
    private javax.swing.JPanel PDeskripsiFilm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelDeskripsi;
    // End of variables declaration//GEN-END:variables
}
