/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Tiket.PilihTiket;

import Class.Fungsi;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dadan
 */
public class panelPilihFilm extends javax.swing.JPanel {

    /**
     * Creates new form panelPilihFilm
     */
    public String SQL,idJadwal,idFilm;
    Fungsi fungsi = new Fungsi();
    public panelPilihFilm(){
        try {
            initComponents();
            setTampil();
        } catch (SQLException ex) {
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setTampil() throws SQLException{
        setStudio("STUDIO 1", gambarS1,GenreS1,JudulS1,pStudio1);
        setStudio("STUDIO 2", gambarS2,GenreS2,JudulS2,pStudio2);
        setStudio("STUDIO 3", gambarS3,GenreS3,JudulS3,pStudio3);
        setStudio("STUDIO 4", gambarS4,GenreS4,JudulS4,pStudio4);
        setStudio("STUDIO 5", gambarS5,GenreS5,JudulS5,pStudio5);
        
    }
    public void setStudio( String Studio, JLabel labelGambar, JLabel Genre , JLabel Judul, JPanel panel) throws SQLException{
        String data[] = new String[1];
        ResultSet res = null;
        res =  koneksi.lihatData( "SELECT `ID_Jadwal` FROM jadwal WHERE `Studio`='"+Studio+"'");
        while (res.next()){
            data[0]= res.getString(1);
        }
        if(data[0] != null){
            idJadwal = data[0];
            data = new String[1];
            data =  koneksi.ambilData(1, "SELECT `ID_Film` FROM jadwal WHERE ID_Jadwal='"+idJadwal+"'");
            idFilm = data[0];
            labelGambar.setIcon( fungsi.gtGambar("Poster", "SELECT Poster FROM film WHERE ID_Film = '"+idFilm+"'",151,177));
            data = new String[2];
            res =  koneksi.lihatData("SELECT `Nama_Genre`, `Judul_Film` FROM film JOIN `film.genre` USING (`ID_Genre`) WHERE `ID_Film`='"+idFilm+"'");
            while (res.next()){
                for (int i = 0; i < 2; i++) {
                    data[i]= res.getString(i+1);
                }
            }  
            Genre.setText(data[0]);
            Judul.setText(data[1]);
            
            data = new String[1];
            SQL = "SELECT `ID_Jadwal` FROM `jadwal.jam` WHERE `Jam_Tayang`>NOW() AND `ID_Jadwal`='"+idJadwal+"' GROUP BY `ID_Jadwal`";
            res =  koneksi.lihatData( SQL);
            while (res.next()){
                data[0]= res.getString(1);
            }
            if(data[0] == null){
                panel.setVisible(false);
            }
            
        }else{
            panel.setVisible(false);
        }
    }
    
    public void tampilFilm(String studio) throws SQLException{
         koneksi.updateData("DELETE FROM dummyHelp");
         koneksi.updateData("INSERT INTO `dummyHelp` (`akses`) VALUES ('"+studio+"');");
        Menu.Tiket.panelTiketUtama.formpilihtiket.JS.setViewportView(new panelDeskripsiPilihFilm());
        Menu.Tiket.panelTiketUtama.formpilihtiket.jPanel2.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pStudio1 = new javax.swing.JPanel();
        lStudio1 = new javax.swing.JLabel();
        GenreS1 = new javax.swing.JLabel();
        JudulS1 = new javax.swing.JLabel();
        gambarS1 = new javax.swing.JLabel();
        pStudio2 = new javax.swing.JPanel();
        lStudio2 = new javax.swing.JLabel();
        GenreS2 = new javax.swing.JLabel();
        JudulS2 = new javax.swing.JLabel();
        gambarS2 = new javax.swing.JLabel();
        pStudio3 = new javax.swing.JPanel();
        lStudio3 = new javax.swing.JLabel();
        GenreS3 = new javax.swing.JLabel();
        JudulS3 = new javax.swing.JLabel();
        gambarS3 = new javax.swing.JLabel();
        pStudio4 = new javax.swing.JPanel();
        lStudio4 = new javax.swing.JLabel();
        GenreS4 = new javax.swing.JLabel();
        JudulS4 = new javax.swing.JLabel();
        gambarS4 = new javax.swing.JLabel();
        pStudio5 = new javax.swing.JPanel();
        lStudio5 = new javax.swing.JLabel();
        GenreS5 = new javax.swing.JLabel();
        JudulS5 = new javax.swing.JLabel();
        gambarS5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        pStudio1.setBackground(new java.awt.Color(204, 255, 255));
        pStudio1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lStudio1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lStudio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStudio1.setText("STUDIO 1");

        GenreS1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        GenreS1.setText("Genre");

        JudulS1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        JudulS1.setText("<HTML>Judul Film Ini Sangat Sangat Panjang Sekali</HTML>");
        JudulS1.setToolTipText("");
        JudulS1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        gambarS1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gambarS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gambarS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarS1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pStudio1Layout = new javax.swing.GroupLayout(pStudio1);
        pStudio1.setLayout(pStudio1Layout);
        pStudio1Layout.setHorizontalGroup(
            pStudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lStudio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pStudio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulS1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GenreS1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(gambarS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudio1Layout.setVerticalGroup(
            pStudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudio1Layout.createSequentialGroup()
                .addComponent(lStudio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarS1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenreS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulS1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pStudio2.setBackground(new java.awt.Color(204, 255, 255));
        pStudio2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lStudio2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lStudio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStudio2.setText("STUDIO 2");

        GenreS2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        GenreS2.setText("Genre");

        JudulS2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        JudulS2.setText("<HTML>Judul Film Ini Sangat Sangat Panjang Sekali</HTML>");
        JudulS2.setToolTipText("");
        JudulS2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        gambarS2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gambarS2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gambarS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarS2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pStudio2Layout = new javax.swing.GroupLayout(pStudio2);
        pStudio2.setLayout(pStudio2Layout);
        pStudio2Layout.setHorizontalGroup(
            pStudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lStudio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pStudio2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulS2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GenreS2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(gambarS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudio2Layout.setVerticalGroup(
            pStudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudio2Layout.createSequentialGroup()
                .addComponent(lStudio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarS2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenreS2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulS2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pStudio3.setBackground(new java.awt.Color(204, 255, 255));
        pStudio3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lStudio3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lStudio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStudio3.setText("STUDIO 3");

        GenreS3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        GenreS3.setText("Genre");

        JudulS3.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        JudulS3.setText("<HTML>Judul Film Ini Sangat Sangat Panjang Sekali</HTML>");
        JudulS3.setToolTipText("");
        JudulS3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        gambarS3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gambarS3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gambarS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarS3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pStudio3Layout = new javax.swing.GroupLayout(pStudio3);
        pStudio3.setLayout(pStudio3Layout);
        pStudio3Layout.setHorizontalGroup(
            pStudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lStudio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pStudio3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulS3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GenreS3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(gambarS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudio3Layout.setVerticalGroup(
            pStudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudio3Layout.createSequentialGroup()
                .addComponent(lStudio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarS3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenreS3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulS3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pStudio4.setBackground(new java.awt.Color(204, 255, 255));
        pStudio4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lStudio4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lStudio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStudio4.setText("STUDIO 4");

        GenreS4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        GenreS4.setText("Genre");

        JudulS4.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        JudulS4.setText("<HTML>Judul Film Ini Sangat Sangat Panjang Sekali</HTML>");
        JudulS4.setToolTipText("");
        JudulS4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        gambarS4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gambarS4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gambarS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarS4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pStudio4Layout = new javax.swing.GroupLayout(pStudio4);
        pStudio4.setLayout(pStudio4Layout);
        pStudio4Layout.setHorizontalGroup(
            pStudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lStudio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pStudio4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulS4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GenreS4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(gambarS4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudio4Layout.setVerticalGroup(
            pStudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudio4Layout.createSequentialGroup()
                .addComponent(lStudio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarS4, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenreS4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulS4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pStudio5.setBackground(new java.awt.Color(204, 255, 255));
        pStudio5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lStudio5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lStudio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStudio5.setText("STUDIO 5");

        GenreS5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        GenreS5.setText("Genre");

        JudulS5.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        JudulS5.setText("<HTML>Judul Film Ini Sangat Sangat Panjang Sekali</HTML>");
        JudulS5.setToolTipText("");
        JudulS5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        gambarS5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gambarS5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gambarS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarS5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pStudio5Layout = new javax.swing.GroupLayout(pStudio5);
        pStudio5.setLayout(pStudio5Layout);
        pStudio5Layout.setHorizontalGroup(
            pStudio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lStudio5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pStudio5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStudio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JudulS5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GenreS5, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(gambarS5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudio5Layout.setVerticalGroup(
            pStudio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudio5Layout.createSequentialGroup()
                .addComponent(lStudio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarS5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenreS5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulS5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void gambarS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarS1MouseClicked
        try {
            tampilFilm("STUDIO 1");
        } catch (SQLException ex) {
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gambarS1MouseClicked

    private void gambarS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarS2MouseClicked
        // TODO add your handling code here:
        try {
            tampilFilm("STUDIO 2");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gambarS2MouseClicked

    private void gambarS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarS3MouseClicked
        // TODO add your handling code here:
        try {
            tampilFilm("STUDIO 3");
        } catch (SQLException ex) {
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gambarS3MouseClicked

    private void gambarS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarS4MouseClicked
        // TODO add your handling code here:
        try {
            tampilFilm("STUDIO 4");
        } catch (SQLException ex) {
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gambarS4MouseClicked

    private void gambarS5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarS5MouseClicked
        // TODO add your handling code here:
        try {
            tampilFilm("STUDIO 5");
        } catch (SQLException ex) {
            Logger.getLogger(panelPilihFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gambarS5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenreS1;
    private javax.swing.JLabel GenreS2;
    private javax.swing.JLabel GenreS3;
    private javax.swing.JLabel GenreS4;
    private javax.swing.JLabel GenreS5;
    private javax.swing.JLabel JudulS1;
    private javax.swing.JLabel JudulS2;
    private javax.swing.JLabel JudulS3;
    private javax.swing.JLabel JudulS4;
    private javax.swing.JLabel JudulS5;
    public javax.swing.JLabel gambarS1;
    public javax.swing.JLabel gambarS2;
    public javax.swing.JLabel gambarS3;
    public javax.swing.JLabel gambarS4;
    public javax.swing.JLabel gambarS5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lStudio1;
    private javax.swing.JLabel lStudio2;
    private javax.swing.JLabel lStudio3;
    private javax.swing.JLabel lStudio4;
    private javax.swing.JLabel lStudio5;
    public javax.swing.JPanel pStudio1;
    public javax.swing.JPanel pStudio2;
    public javax.swing.JPanel pStudio3;
    public javax.swing.JPanel pStudio4;
    public javax.swing.JPanel pStudio5;
    // End of variables declaration//GEN-END:variables
}
