/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Class.Fungsi;
//import static Main.panelLogin.panellogin;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanii
 */
public class formMenu extends javax.swing.JFrame {

    /**
     * Creates new form formMenu
     */
    public static formMenu menu = new formMenu();
    Fungsi fungsi = new Fungsi();
     
    public formMenu() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println( ex.getMessage());
        } catch (InstantiationException ex) {
            System.out.println( ex.getMessage());
        } catch (IllegalAccessException ex) {
            System.out.println( ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println( ex.getMessage());
        }
        //</editor-fold>
        initComponents();
        this.addWindowListener(new WindowAdapter() {
                        @Override
                    public void windowClosing(WindowEvent evt) {
                        int konf = JOptionPane.showConfirmDialog(null, "YAKIN INGIN KELUAR? \n\n", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                        if(konf==JOptionPane.YES_OPTION){
                            try {
                                koneksi.tutupKoneksi();
                                System.exit(0);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                        }else{
                            try {
                                wait();
                            } catch (InterruptedException ex) {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                            
                        }
                        //super.windowClosing(evt); //To change body of generated methods, choose Tools | Templates.
                    }
                    });
     //   panellogin = new panelLogin();
        LTanggal.setText(fungsi.gettanggal());
        fungsi.gettimer(LJam);
        
        JS.setViewportView(new panelLogin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        LJam = new javax.swing.JLabel();
        LTanggal = new javax.swing.JLabel();
        JS = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bandung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 0, 120);
        jPanel9.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ist*na Plaza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1, 0, 0);
        jPanel9.add(jLabel12, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Broadway", 0, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("XXI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
        jPanel9.add(jLabel10, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Vivaldi", 0, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cinema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 120, 0, 0);
        jPanel9.add(jLabel13, gridBagConstraints);

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        LJam.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        LJam.setForeground(new java.awt.Color(255, 255, 255));
        LJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJam.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 11, 138);
        jPanel10.add(LJam, gridBagConstraints);

        LTanggal.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        LTanggal.setForeground(new java.awt.Color(255, 255, 255));
        LTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTanggal.setText("yyyy-MM-dd");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 86, 11, 0);
        jPanel10.add(LTanggal, gridBagConstraints);

        getContentPane().add(jPanel10, java.awt.BorderLayout.PAGE_END);

        JS.setBackground(new java.awt.Color(204, 255, 255));
        JS.setBorder(null);
        getContentPane().add(JS, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println( ex.getMessage());
        } catch (InstantiationException ex) {
            System.out.println(  ex.getMessage());
        } catch (IllegalAccessException ex) {
            System.out.println( ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println( ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane JS;
    private javax.swing.JLabel LJam;
    private javax.swing.JLabel LTanggal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
