/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Class.Fungsi;
import static Main.formMenu.menu;
import static Main.panelIdentitas.panelidentitas;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import com.placeholder.PlaceHolder;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hanii
 */
public class panelLogin extends javax.swing.JPanel {

    /**
     * Creates new form panelLogin
     */
    Fungsi fungsi = new Fungsi();
 //   public static panelLogin panellogin = new panelLogin();    
    JPanel JP = new JPanel();
    public panelLogin() {
        initComponents();
        
        PlaceHolder username = new PlaceHolder(TFUsername, "Username");
        PlaceHolder password = new PlaceHolder(TFPassword, "Password");
        TFUsername.setDocument(fungsi.getToUpperCase());
    }
    
    public  void login() throws SQLException{
        
        String data[] = new String[1];
        String username = TFUsername.getText();
        String password = TFPassword.getText();
        ResultSet res = null;
        res = koneksi.lihatData("SELECT * FROM `karyawan.akunlogin` WHERE username = '"+username+"'");
        if(res==null){
            JOptionPane.showMessageDialog(null, "DATA BELUM ADA \n\n HUBUNGI ADMIN UNTUK LOGIN");
        }else{
            if(res.next()){
                if(password.equals(res.getString("password"))){
                    
                    koneksi.updateData("DELETE FROM dummyHelp");
                    koneksi.updateData("INSERT INTO `dummyHelp` (`akses`) VALUES ('"+username+"')");
                    
                    data = koneksi.ambilData(1, "SELECT karyawan.Jabatan FROM karyawan,`karyawan.akunlogin` WHERE `karyawan.akunlogin`.`username`='"+username+"' AND `karyawan.akunlogin`.`id_karyawan`=karyawan.`ID_Karyawan`");
                    if(data[0].equals("STAFF ADMINISTRASI")){
                        panelidentitas = new panelIdentitas();
                        JOptionPane.showMessageDialog(null, "LOGIN " + username + " BERHASIL . . ." ,"Login",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("IMAGE\boss-icon.png"));
                        
                        menu.JS.setViewportView(panelidentitas);
                    }else if(data[0].equals("KASIR")){
                        panelidentitas = new panelIdentitas();                       
                        menu.JS.setViewportView(panelidentitas);
                    }
                    
                }else{
                        JOptionPane.showMessageDialog(null, "PASWORD SALAH ! \n\n SILAHKAN ULANGI");
                        TFPassword.setText("");
                        TFPassword.requestFocus();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "User tidak ditemukan");
                    TFUsername.setText("");
                    TFPassword.setText("");
                    TFUsername.requestFocus();

            }
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Akses = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TFUsername = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TFPassword = new javax.swing.JPasswordField();
        BLogin = new javax.swing.JButton();

        Akses.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        Akses.setText("Lupa Password?");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        jLabel8.setText("Lupa Password?");

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registration-icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 86, 0, 0);
        jPanel9.add(jLabel5, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/boss-icon.png"))); // NOI18N

        TFUsername.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        TFUsername.setBorder(null);
        TFUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFUsernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFUsernameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(TFUsername)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Security-Password-2-icon (2).png"))); // NOI18N

        TFPassword.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TFPassword.setBorder(null);
        TFPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFPasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(TFPassword)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BLogin.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        BLogin.setText("LOGIN");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 13, 12);
        jPanel9.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        try {
            // TODO add your handling code here:
            login();
        } catch (SQLException ex) {
            System.out.println( ex.getMessage());
        }
    }//GEN-LAST:event_BLoginActionPerformed

    private void TFPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPasswordKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(karakter==KeyEvent.VK_ENTER){
            try {
                login();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_TFPasswordKeyTyped

    private void TFUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsernameKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(karakter==KeyEvent.VK_ENTER){
            try {
                login();
            } catch (SQLException ex) {
                System.out.println( ex.getMessage());
            }
        }
    }//GEN-LAST:event_TFUsernameKeyTyped

    private void TFUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUsernameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akses;
    private javax.swing.JButton BLogin;
    private javax.swing.JPasswordField TFPassword;
    private javax.swing.JTextField TFUsername;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
