/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Class.Fungsi;
import static Main.formMenu.menu;
import static Main.panelIdentitas.panelidentitas;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Hanii
 */
public class panelAkunSaya extends javax.swing.JPanel {

    /**
     * Creates new form panelAkunSaya
     */
    private String statusAktif, SQL,username,password;
    private String idKaryawan, namaKaryawan, noTlpK, tmptLahirK, tglLahirK, jenisKlmnK, jalanK,
                noRumahK,provinsiK,kabKotaK,kecamatanK,kelurahanK, rtK,rwK, statusKawinK, tglKerjaK,jabatanK;
        
    int row = 0;
    Statement stat = koneksi.getSt();
    Fungsi fungsi = new Fungsi();
    
    public panelAkunSaya() {
        initComponents();
        TampilDataKaryawan();
    }
    
    public void setAkses(){
        this.idKaryawan = panelidentitas.LID.getText();
        
    }
    
        private void TampilDataKaryawan(){
        try {
            setAkses();
            String data[] = koneksi.ambilData(19, "SELECT * FROM karyawan WHERE ID_KARYAWAN='"+idKaryawan+"' ");
            String datas[] = koneksi.ambilData(3, "SELECT * FROM `karyawan.akunlogin` WHERE ID_KARYAWAN='"+idKaryawan+"' ");
            Date tglLahir,tglKerja;
            String tanggalLahir = data[4];
            tglLahir = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalLahir);
            String tanggalKerja = data[15];
            tglKerja = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalKerja);
            LIDKaryawan.setText(data[0]);
            LNamaKaryawan.setText(data[1]); //clear tambah film
            LNoTelepon.setText(data[2]);
            LTempatLahirK.setText(data[3]);
            LTanggalLahirK.setText(data[4]);
            LJenisKK.setText(data[5]);
            LAlamat.setText(data[6]+" NO "+data[7]);
            LProvinsi.setText(data[8]);
            LKabKota.setText(data[9]);
            LKecamatan.setText(data[10]);
            LKelDesa.setText(data[11]);
            LRTRW.setText(data[12]+"/"+data[13]);
            LStatusKawin.setText(data[14]);
            LTglKerja.setText(data[15]+" s/d "+data[17]);
            LJabatan.setText(data[16]);
            jLabelGambar.setIcon(fungsi.gtGambar("FotoKaryawan", "SELECT Foto FROM karyawan WHERE ID_Karyawan = '"+idKaryawan+"'",151,177));
            LUsername.setText(datas[0]);
        } catch (SQLException | ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        BGantiUsernameSaya = new javax.swing.JButton();
        BGantPasswordSaya = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        LNamaKaryawan = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        LNoTelepon = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        LStatusKawin = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        LTempatLahirK = new javax.swing.JLabel();
        LTanggalLahirK = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        LJenisKK = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LKecamatan = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        LKabKota = new javax.swing.JLabel();
        LProvinsi = new javax.swing.JLabel();
        LKelDesa = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        LIDKaryawan = new javax.swing.JLabel();
        LDusunKampung2 = new javax.swing.JLabel();
        LRTRW = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        LJabatan = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        LTglKerja = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        LJabatanAS1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jPanel38.setBackground(new java.awt.Color(204, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BGantiUsernameSaya.setBackground(new java.awt.Color(153, 255, 153));
        BGantiUsernameSaya.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BGantiUsernameSaya.setText("GANTI USERNAME");
        BGantiUsernameSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGantiUsernameSayaActionPerformed(evt);
            }
        });

        BGantPasswordSaya.setBackground(new java.awt.Color(153, 255, 153));
        BGantPasswordSaya.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BGantPasswordSaya.setText("GANTI PASSWORD");
        BGantPasswordSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGantPasswordSayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BGantiUsernameSaya, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BGantPasswordSaya, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel38Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BGantPasswordSaya, BGantiUsernameSaya});

        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGantiUsernameSaya)
                    .addComponent(BGantPasswordSaya))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel38Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BGantPasswordSaya, BGantiUsernameSaya});

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        LNamaKaryawan.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        LNamaKaryawan.setText("NAMA KARYAWAN");

        LUsername.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LUsername.setText("Username");

        jLabel93.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel93.setText("•");

        LNoTelepon.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LNoTelepon.setText("No Telepon");

        jLabel94.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel94.setText("•");

        LStatusKawin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LStatusKawin.setText("StatusKawin");

        jPanel19.setBackground(new java.awt.Color(204, 255, 255));

        LTempatLahirK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTempatLahirK.setText("Tempat lahir");

        LTanggalLahirK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTanggalLahirK.setText("Tanggal Lahir");

        jLabel97.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel97.setText(",");

        LJenisKK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LJenisKK.setText("Jenis Kelamin");

        LAlamat.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LAlamat.setText("Alamat Asal/Jalan");

        LKecamatan.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKecamatan.setText("Kecamatan");

        jLabel128.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel128.setText(",");

        LKabKota.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKabKota.setText("Kabupaten/kota");

        LProvinsi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LProvinsi.setText("Provinsi");

        LKelDesa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKelDesa.setText("Kelurahan/Desa");

        jLabel134.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel134.setText(",");

        LIDKaryawan.setBackground(new java.awt.Color(255, 0, 51));
        LIDKaryawan.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        LIDKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        LIDKaryawan.setText("ID Karyawan");

        LDusunKampung2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LDusunKampung2.setText("RT/RW");

        LRTRW.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LRTRW.setText("RT/RW");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(LKelDesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel134)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LKecamatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel128)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LKabKota)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(LAlamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LDusunKampung2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LRTRW))
                            .addComponent(LIDKaryawan)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(LTempatLahirK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel97)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LTanggalLahirK))
                            .addComponent(LJenisKK)
                            .addComponent(LProvinsi))
                        .addContainerGap(174, Short.MAX_VALUE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LIDKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTempatLahirK)
                    .addComponent(LTanggalLahirK)
                    .addComponent(jLabel97))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LJenisKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAlamat)
                    .addComponent(LDusunKampung2)
                    .addComponent(LRTRW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKelDesa)
                    .addComponent(LKecamatan)
                    .addComponent(jLabel128)
                    .addComponent(LKabKota)
                    .addComponent(jLabel134))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LProvinsi)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(204, 255, 255));

        LJabatan.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        LJabatan.setText("JABATAN");

        jLabel137.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel137.setText("MASA JABATAN");

        LTglKerja.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTglKerja.setText("Tanggal Bekerja");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJabatan)
                    .addComponent(jLabel137)
                    .addComponent(LTglKerja))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel137)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTglKerja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGambarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNamaKaryawan)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(LUsername)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel93)
                        .addGap(18, 18, 18)
                        .addComponent(LNoTelepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel94)
                        .addGap(18, 18, 18)
                        .addComponent(LStatusKawin))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNamaKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel94)
                        .addComponent(LStatusKawin))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LUsername)
                        .addComponent(jLabel93)
                        .addComponent(LNoTelepon)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LJabatanAS1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        LJabatanAS1.setText("*) Hubungi Staff Administrasi Jika Lupa Password/Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LJabatanAS1)
                    .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LJabatanAS1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BGantiUsernameSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGantiUsernameSayaActionPerformed
        // TODO add your handling code here:
        JPasswordField pf = new JPasswordField();
        int ok= JOptionPane.showOptionDialog(this, new Object[] {"Masukan Password Anda", pf}, "Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
        //  int ok = JOptionPane.showConfirmDialog(null, pf, "Enter Password",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(ok==JOptionPane.OK_OPTION){
            try {
                String input = new String(pf.getPassword());
                String[] data = new String[1];
                data = koneksi.ambilData(1, "SELECT password from `karyawan.akunlogin` where username = '"+LUsername.getText()+"'");
                
                String pss   = data[0];
                
                if(input.equals(pss)){
                    JTextField tx = new JTextField();
                    tx.setDocument(fungsi.getToUpperCase());
                    //tx.setDocument(new SaringKarakter().getToUpperCase());
                    int gnt= JOptionPane.showOptionDialog(this, new Object[] {"Masukan Username Baru",tx}, "Ganti Username", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
                    if(gnt==JOptionPane.OK_OPTION){
                        if(tx.equals(null)){
                            JOptionPane.showMessageDialog(null, "Username Kosong");
                        }else{
                        String ganti = new String(tx.getText());
                        try{
                            SQL = "UPDATE `karyawan.akunlogin` set "
                                    + "username= '"+ganti+"'"
                                    + "WHERE username = '"+LUsername.getText()+"'";
                            stat.executeUpdate(SQL);
                            JOptionPane.showMessageDialog(null, "Username Berhasil Diganti");
                            menu.JS.setViewportView(new panelLogin());
                        }catch(Exception ex){
                            JOptionPane.showMessageDialog(null, "Username Sudah Ada!"+ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
                        }
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Password Salah!!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_BGantiUsernameSayaActionPerformed

    private void BGantPasswordSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGantPasswordSayaActionPerformed
        // TODO add your handling code here:
        JPasswordField pf = new JPasswordField();
        int ok= JOptionPane.showOptionDialog(this, new Object[] {"Masukan Password Lama", pf}, "Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
        if(ok==JOptionPane.OK_OPTION){
            try {
                String input = new String(pf.getPassword());
                String[] data = new String[1];
                data = koneksi.ambilData(1, "SELECT password from `karyawan.akunlogin` where username = '"+LUsername.getText()+"'");
                
                String pss   = data[0];
                
                if(input.equals(pss)){
                    JPasswordField tx = new JPasswordField();
                    int gnt= JOptionPane.showOptionDialog(this, new Object[] {"Masukan Password Baru",tx}, "Ganti Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
                    if(gnt==JOptionPane.OK_OPTION){
                        if(tx.equals(null)){
                            JOptionPane.showMessageDialog(null, "Username Kosong");
                        }else{
                        String ganti = new String(tx.getPassword());
                        JPasswordField ty = new JPasswordField();
                        int conf= JOptionPane.showOptionDialog(this, new Object[] {"Konfirmasi Password",ty}, "Ganti Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
                        if(conf==JOptionPane.OK_OPTION){
                            String confirm = new String(ty.getPassword());
                            if(confirm.equals(ganti)){
                                try{
                                   
                                    SQL = "UPDATE `karyawan.akunlogin` set "
                                            + "password= '"+ganti+"'"
                                            + "WHERE username = '"+LUsername.getText()+"'";
                                    stat.executeUpdate(SQL);
                                    JOptionPane.showMessageDialog(null, "Password Berhasil Diganti! \n Silahkan Login Ulang");
                                    menu.JS.setViewportView(new panelLogin());
                                }catch(Exception ex){JOptionPane.showMessageDialog(null, "Username Sudah Ada!", "Error", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Password Tidak Cocok");
                            }
                        }
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Password Salah!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(panelAkunSaya.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BGantPasswordSayaActionPerformed

    private void jLabelGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGambarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelGambarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(LJabatan.getText().equals("KASIR")){
                panelidentitas.JS.setViewportView(new panelMenuKasir());
            }else{
                panelidentitas.JS.setViewportView(new panelMenuStaff());
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGantPasswordSaya;
    private javax.swing.JButton BGantiUsernameSaya;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LDusunKampung2;
    private javax.swing.JLabel LIDKaryawan;
    private javax.swing.JLabel LJabatan;
    private javax.swing.JLabel LJabatanAS1;
    private javax.swing.JLabel LJenisKK;
    private javax.swing.JLabel LKabKota;
    private javax.swing.JLabel LKecamatan;
    private javax.swing.JLabel LKelDesa;
    private javax.swing.JLabel LNamaKaryawan;
    private javax.swing.JLabel LNoTelepon;
    private javax.swing.JLabel LProvinsi;
    private javax.swing.JLabel LRTRW;
    private javax.swing.JLabel LStatusKawin;
    private javax.swing.JLabel LTanggalLahirK;
    private javax.swing.JLabel LTempatLahirK;
    private javax.swing.JLabel LTglKerja;
    private javax.swing.JLabel LUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
