/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Karyawan;

import Class.Fungsi;
import static Main.panelIdentitas.panelidentitas;
import static aplikasitiketbioskop.AplikasiTiketBioskop.koneksi;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanii
 */
public class panelDeskripsiK extends javax.swing.JPanel {

    /**
     * Creates new form panelDeskripsiK
     */
    Fungsi fungsi = new Fungsi();
     private String tampilan = "yyyy-MM-dd";
    SimpleDateFormat format = new SimpleDateFormat(tampilan);
    private String tempPassword = "ddMMyyyy";
    SimpleDateFormat formatPassword = new SimpleDateFormat(tempPassword);
    
    private String statusAktif, SQL,username,password;
    private String idKaryawan, namaKaryawan, noTlpK, tmptLahirK, tglLahirK, jenisKlmnK, jalanK,
                noRumahK,provinsiK,kabKotaK,kecamatanK,kelurahanK, rtK,rwK, statusKawinK, tglKerjaK,jabatanK;
        
    int row = 0;
    public panelDeskripsiK(){
        initComponents();
        TampilDataKaryawan();
    }
    
    public void setAkses() throws SQLException{
        String data[] = new String[1];
        data =  koneksi.ambilData(1,"SELECT * FROM dummyHelp");
        this.idKaryawan = data[0];
    }
    
    private void TampilDataKaryawan(){
        try {
            setAkses();
            String data[] =  koneksi.ambilData(19, "SELECT * FROM karyawan WHERE karyawan.ID_KARYAWAN='"+idKaryawan+"' ");
            Date tglLahir,tglKerja;
            String tanggalLahir = data[4];
            tglLahir = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalLahir);
            String tanggalKerja = data[15];
            tglKerja = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalKerja);
            LIDKaryawan.setText(data[0]);
            LNamaKaryawan.setText(data[1]); //clear tambah film
            LNoTelepon.setText(data[2]);
            LTempatLahirK.setText(data[3]);
            LTanggalLahirK.setText(data[4]);
            LJenisKK.setText(data[5]);
            LAlamat.setText(data[6]+" NO "+data[7]);
            LProvinsi.setText(data[8]);
            LKabKota.setText(data[9]);
            LKecamatan.setText(data[10]);
            LKelDesa.setText(data[11]);
            LRTRW.setText(data[12]+"/"+data[13]);
            LStatusKawin.setText(data[14]);
            LTglKerja.setText(data[15]+" s/d "+data[17]);
            LJabatan.setText(data[16]);
            statusAktif = data[18];
            jLabelGambar.setIcon( fungsi.gtGambar("FotoKaryawan", "SELECT Foto FROM karyawan WHERE ID_Karyawan = '"+idKaryawan+"'",151,177));
            // LUsername.setText(statusAktif);
            String dataa[] =  koneksi.ambilData(1, "SELECT username FROM `karyawan.akunlogin` WHERE id_karyawan='"+idKaryawan+"' ");
            if(statusAktif.equals("AKTIF")){
                LUsername.setText(dataa[0]);
                LStatus.setText("");
                BPecatKaryawan.setEnabled(true);
                BKerjaKembali.setVisible(false);
                jButton2.setEnabled(true);
            }else if(statusAktif.equals("TIDAK AKTIF")){
                LUsername.setText("-");
                LStatus.setText("SUDAH TIDAK BEKERJA");
                BPecatKaryawan.setEnabled(false);
                BKerjaKembali.setVisible(true);
                jButton2.setEnabled(false);
            }
        } catch (SQLException | ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LNamaKaryawan = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        LUsername = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        LNoTelepon = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        LTempatLahirK = new javax.swing.JLabel();
        LTanggalLahirK = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        LJenisKK = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LKecamatan = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        LKabKota = new javax.swing.JLabel();
        LProvinsi = new javax.swing.JLabel();
        LKelDesa = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        LIDKaryawan = new javax.swing.JLabel();
        LDusunKampung1 = new javax.swing.JLabel();
        LRTRW = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        LJabatan = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        LTglKerja = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        LStatusKawin = new javax.swing.JLabel();
        LStatus = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        BKerjaKembali = new javax.swing.JButton();
        BPecatKaryawan = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon (1).png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        LNamaKaryawan.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        LNamaKaryawan.setText("NAMA KARYAWAN");

        LUsername.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LUsername.setText("Username");

        jLabel91.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel91.setText("•");

        LNoTelepon.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LNoTelepon.setText("No Telepon");

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));

        LTempatLahirK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTempatLahirK.setText("Tempat lahir");

        LTanggalLahirK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTanggalLahirK.setText("Tanggal Lahir");

        jLabel96.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel96.setText(",");

        LJenisKK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LJenisKK.setText("Jenis Kelamin");

        LAlamat.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LAlamat.setText("Alamat Asal/Jalan");

        LKecamatan.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKecamatan.setText("Kecamatan");

        jLabel127.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel127.setText(",");

        LKabKota.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKabKota.setText("Kabupaten/kota");

        LProvinsi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LProvinsi.setText("Provinsi");

        LKelDesa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LKelDesa.setText("Kelurahan/Desa");

        jLabel133.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel133.setText(",");

        LIDKaryawan.setBackground(new java.awt.Color(255, 0, 51));
        LIDKaryawan.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        LIDKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        LIDKaryawan.setText("ID Karyawan");

        LDusunKampung1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LDusunKampung1.setText("RT/RW");

        LRTRW.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LRTRW.setText("RT/RW");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(LKelDesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel133)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LKecamatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel127)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LKabKota)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(LAlamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LDusunKampung1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LRTRW))
                            .addComponent(LIDKaryawan)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(LTempatLahirK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel96)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LTanggalLahirK))
                            .addComponent(LJenisKK)
                            .addComponent(LProvinsi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LIDKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTempatLahirK)
                    .addComponent(LTanggalLahirK)
                    .addComponent(jLabel96))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LJenisKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAlamat)
                    .addComponent(LDusunKampung1)
                    .addComponent(LRTRW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKelDesa)
                    .addComponent(LKecamatan)
                    .addComponent(jLabel127)
                    .addComponent(LKabKota)
                    .addComponent(jLabel133))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LProvinsi)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));

        LJabatan.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        LJabatan.setText("JABATAN");

        jLabel136.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel136.setText("MASA JABATAN");

        LTglKerja.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LTglKerja.setText("Tanggal Bekerja");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJabatan)
                    .addComponent(jLabel136)
                    .addComponent(LTglKerja))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTglKerja)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel92.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel92.setText("•");

        LStatusKawin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LStatusKawin.setText("StatusKawin");

        LStatus.setBackground(new java.awt.Color(255, 0, 51));
        LStatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LStatus.setForeground(new java.awt.Color(255, 0, 0));
        LStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LStatus.setText("SUDAH TIDAK BEKERJA");

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGambarMouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-validated-icon.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BKerjaKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/send-icon.png"))); // NOI18N
        BKerjaKembali.setContentAreaFilled(false);
        BKerjaKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKerjaKembaliActionPerformed(evt);
            }
        });

        BPecatKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/remove-user-icon.png"))); // NOI18N
        BPecatKaryawan.setContentAreaFilled(false);
        BPecatKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPecatKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(LUsername)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel91)
                                .addGap(18, 18, 18)
                                .addComponent(LNoTelepon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel92)
                                .addGap(18, 18, 18)
                                .addComponent(LStatusKawin))
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BKerjaKembali, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BPecatKaryawan, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LStatus)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel92)
                                .addComponent(LStatusKawin))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LUsername)
                                .addComponent(jLabel91)
                                .addComponent(LNoTelepon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BPecatKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(BKerjaKembali)))
                .addGap(18, 18, 18)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGambarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelGambarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
       panelidentitas.JS.setViewportView(new panelEditKaryawan());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        panelidentitas.JS.setViewportView(new panelTabelKaryawan());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BPecatKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPecatKaryawanActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(null, "Pecat "+LNamaKaryawan.getText()+"? \n Data Karyawan Akan Tetap Tersimpan ", "Pecat Karyawan", JOptionPane.YES_NO_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            try {
                statusAktif= "TIDAK AKTIF";
                 koneksi.updateData("UPDATE karyawan set Tanggal_Keluar_Kerja = '"+ fungsi.gettanggal()+"', Status_Aktif='"+statusAktif+"' where id_karyawan = '"+idKaryawan+"'");
                 koneksi.updateData("DELETE FROM `karyawan.akunlogin` WHERE `ID_Karyawan` ='"+idKaryawan+"'");
                JOptionPane.showMessageDialog(null, "KARYAWAN TELAH DIPECAT \n\n DATA KARYAWAN MASIH BISA DILIHAT","Pecat Karyawan",JOptionPane.INFORMATION_MESSAGE);
                panelidentitas.JS.setViewportView(new panelDeskripsiK());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_BPecatKaryawanActionPerformed

    private void BKerjaKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKerjaKembaliActionPerformed
        // TODO add your handling code here:
        JDateChooser JDS = new JDateChooser();
        int konfirmasi=JOptionPane.showConfirmDialog(null, "Kerjakan Kembali "+LNamaKaryawan.getText()+"?", "Pekerjakan Kembali Karyawan", JOptionPane.YES_NO_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            int gnt= JOptionPane.showOptionDialog(this, new Object[] {"MASUKAN TANGGAL LAHIR \n\n",JDS}, null, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] {"OK", "CANCEL"}, null);
            if(gnt==JOptionPane.OK_OPTION){
                try {
                    statusAktif = "AKTIF";
                    username        = idKaryawan;
                    password        = String.valueOf(formatPassword.format(JDS.getDate()));
                     koneksi.updateData("UPDATE karyawan set Tanggal_Masuk_Kerja = '"+ fungsi.gettanggal()+"',Tanggal_Keluar_Kerja = null, Status_Aktif='"+statusAktif+"' where id_karyawan = '"+idKaryawan+"'");
                     koneksi.updateData("INSERT INTO `karyawan.akunlogin` (username, password, id_karyawan) values "
                            + "('"+username+"','"+password+"','"+idKaryawan+"')");
                    JOptionPane.showMessageDialog(null, "Karyawan Telah Bekerja Kembali","Pekerjakan Kembali Karyawan",JOptionPane.INFORMATION_MESSAGE);
                    panelidentitas.JS.setViewportView(new panelDeskripsiK());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            
        }
        }
    }//GEN-LAST:event_BKerjaKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKerjaKembali;
    private javax.swing.JButton BPecatKaryawan;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LDusunKampung1;
    private javax.swing.JLabel LIDKaryawan;
    private javax.swing.JLabel LJabatan;
    private javax.swing.JLabel LJenisKK;
    private javax.swing.JLabel LKabKota;
    private javax.swing.JLabel LKecamatan;
    private javax.swing.JLabel LKelDesa;
    private javax.swing.JLabel LNamaKaryawan;
    private javax.swing.JLabel LNoTelepon;
    private javax.swing.JLabel LProvinsi;
    private javax.swing.JLabel LRTRW;
    private javax.swing.JLabel LStatus;
    private javax.swing.JLabel LStatusKawin;
    private javax.swing.JLabel LTanggalLahirK;
    private javax.swing.JLabel LTempatLahirK;
    private javax.swing.JLabel LTglKerja;
    private javax.swing.JLabel LUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
